language: objective-c
before_install:
   - export LANG=en_US.UTF-8
   - gem install cocoapods
   - gem install xcpretty
   - cd Code && pod install
   - cd ..
script: xcodebuild -workspace Code/UAFilterableResultsController.xcworkspace -scheme UAFilterableResultsController -sdk iphonesimulator7.1 -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch),OS=7.1' clean build test | xcpretty -c